/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DecisionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4239776977085921445L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DecisionEvent\",\"namespace\":\"com.example.avro\",\"fields\":[{\"name\":\"transactionId\",\"type\":\"string\"},{\"name\":\"decision\",\"type\":\"string\"},{\"name\":\"authorisationCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"reasonCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"createdAt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DecisionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DecisionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DecisionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DecisionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DecisionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DecisionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DecisionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DecisionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DecisionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence transactionId;
  private java.lang.CharSequence decision;
  private java.lang.CharSequence authorisationCode;
  private java.lang.CharSequence reasonCode;
  private java.lang.CharSequence createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DecisionEvent() {}

  /**
   * All-args constructor.
   * @param transactionId The new value for transactionId
   * @param decision The new value for decision
   * @param authorisationCode The new value for authorisationCode
   * @param reasonCode The new value for reasonCode
   * @param createdAt The new value for createdAt
   */
  public DecisionEvent(java.lang.CharSequence transactionId, java.lang.CharSequence decision, java.lang.CharSequence authorisationCode, java.lang.CharSequence reasonCode, java.lang.CharSequence createdAt) {
    this.transactionId = transactionId;
    this.decision = decision;
    this.authorisationCode = authorisationCode;
    this.reasonCode = reasonCode;
    this.createdAt = createdAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionId;
    case 1: return decision;
    case 2: return authorisationCode;
    case 3: return reasonCode;
    case 4: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionId = (java.lang.CharSequence)value$; break;
    case 1: decision = (java.lang.CharSequence)value$; break;
    case 2: authorisationCode = (java.lang.CharSequence)value$; break;
    case 3: reasonCode = (java.lang.CharSequence)value$; break;
    case 4: createdAt = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public java.lang.CharSequence getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.CharSequence value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'decision' field.
   * @return The value of the 'decision' field.
   */
  public java.lang.CharSequence getDecision() {
    return decision;
  }


  /**
   * Sets the value of the 'decision' field.
   * @param value the value to set.
   */
  public void setDecision(java.lang.CharSequence value) {
    this.decision = value;
  }

  /**
   * Gets the value of the 'authorisationCode' field.
   * @return The value of the 'authorisationCode' field.
   */
  public java.lang.CharSequence getAuthorisationCode() {
    return authorisationCode;
  }


  /**
   * Sets the value of the 'authorisationCode' field.
   * @param value the value to set.
   */
  public void setAuthorisationCode(java.lang.CharSequence value) {
    this.authorisationCode = value;
  }

  /**
   * Gets the value of the 'reasonCode' field.
   * @return The value of the 'reasonCode' field.
   */
  public java.lang.CharSequence getReasonCode() {
    return reasonCode;
  }


  /**
   * Sets the value of the 'reasonCode' field.
   * @param value the value to set.
   */
  public void setReasonCode(java.lang.CharSequence value) {
    this.reasonCode = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.lang.CharSequence getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.CharSequence value) {
    this.createdAt = value;
  }

  /**
   * Creates a new DecisionEvent RecordBuilder.
   * @return A new DecisionEvent RecordBuilder
   */
  public static com.example.avro.DecisionEvent.Builder newBuilder() {
    return new com.example.avro.DecisionEvent.Builder();
  }

  /**
   * Creates a new DecisionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DecisionEvent RecordBuilder
   */
  public static com.example.avro.DecisionEvent.Builder newBuilder(com.example.avro.DecisionEvent.Builder other) {
    if (other == null) {
      return new com.example.avro.DecisionEvent.Builder();
    } else {
      return new com.example.avro.DecisionEvent.Builder(other);
    }
  }

  /**
   * Creates a new DecisionEvent RecordBuilder by copying an existing DecisionEvent instance.
   * @param other The existing instance to copy.
   * @return A new DecisionEvent RecordBuilder
   */
  public static com.example.avro.DecisionEvent.Builder newBuilder(com.example.avro.DecisionEvent other) {
    if (other == null) {
      return new com.example.avro.DecisionEvent.Builder();
    } else {
      return new com.example.avro.DecisionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DecisionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DecisionEvent>
    implements org.apache.avro.data.RecordBuilder<DecisionEvent> {

    private java.lang.CharSequence transactionId;
    private java.lang.CharSequence decision;
    private java.lang.CharSequence authorisationCode;
    private java.lang.CharSequence reasonCode;
    private java.lang.CharSequence createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.DecisionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.decision)) {
        this.decision = data().deepCopy(fields()[1].schema(), other.decision);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.authorisationCode)) {
        this.authorisationCode = data().deepCopy(fields()[2].schema(), other.authorisationCode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.reasonCode)) {
        this.reasonCode = data().deepCopy(fields()[3].schema(), other.reasonCode);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing DecisionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.DecisionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.decision)) {
        this.decision = data().deepCopy(fields()[1].schema(), other.decision);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.authorisationCode)) {
        this.authorisationCode = data().deepCopy(fields()[2].schema(), other.authorisationCode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.reasonCode)) {
        this.reasonCode = data().deepCopy(fields()[3].schema(), other.reasonCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder setTransactionId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.transactionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder clearTransactionId() {
      transactionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'decision' field.
      * @return The value.
      */
    public java.lang.CharSequence getDecision() {
      return decision;
    }


    /**
      * Sets the value of the 'decision' field.
      * @param value The value of 'decision'.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder setDecision(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.decision = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'decision' field has been set.
      * @return True if the 'decision' field has been set, false otherwise.
      */
    public boolean hasDecision() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'decision' field.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder clearDecision() {
      decision = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'authorisationCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getAuthorisationCode() {
      return authorisationCode;
    }


    /**
      * Sets the value of the 'authorisationCode' field.
      * @param value The value of 'authorisationCode'.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder setAuthorisationCode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.authorisationCode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'authorisationCode' field has been set.
      * @return True if the 'authorisationCode' field has been set, false otherwise.
      */
    public boolean hasAuthorisationCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'authorisationCode' field.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder clearAuthorisationCode() {
      authorisationCode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'reasonCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getReasonCode() {
      return reasonCode;
    }


    /**
      * Sets the value of the 'reasonCode' field.
      * @param value The value of 'reasonCode'.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder setReasonCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.reasonCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'reasonCode' field has been set.
      * @return True if the 'reasonCode' field has been set, false otherwise.
      */
    public boolean hasReasonCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'reasonCode' field.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder clearReasonCode() {
      reasonCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder setCreatedAt(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.createdAt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.example.avro.DecisionEvent.Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DecisionEvent build() {
      try {
        DecisionEvent record = new DecisionEvent();
        record.transactionId = fieldSetFlags()[0] ? this.transactionId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.decision = fieldSetFlags()[1] ? this.decision : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.authorisationCode = fieldSetFlags()[2] ? this.authorisationCode : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.reasonCode = fieldSetFlags()[3] ? this.reasonCode : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DecisionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DecisionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DecisionEvent>
    READER$ = (org.apache.avro.io.DatumReader<DecisionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.transactionId);

    out.writeString(this.decision);

    if (this.authorisationCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.authorisationCode);
    }

    if (this.reasonCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.reasonCode);
    }

    out.writeString(this.createdAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);

      this.decision = in.readString(this.decision instanceof Utf8 ? (Utf8)this.decision : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.authorisationCode = null;
      } else {
        this.authorisationCode = in.readString(this.authorisationCode instanceof Utf8 ? (Utf8)this.authorisationCode : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.reasonCode = null;
      } else {
        this.reasonCode = in.readString(this.reasonCode instanceof Utf8 ? (Utf8)this.reasonCode : null);
      }

      this.createdAt = in.readString(this.createdAt instanceof Utf8 ? (Utf8)this.createdAt : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);
          break;

        case 1:
          this.decision = in.readString(this.decision instanceof Utf8 ? (Utf8)this.decision : null);
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.authorisationCode = null;
          } else {
            this.authorisationCode = in.readString(this.authorisationCode instanceof Utf8 ? (Utf8)this.authorisationCode : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.reasonCode = null;
          } else {
            this.reasonCode = in.readString(this.reasonCode instanceof Utf8 ? (Utf8)this.reasonCode : null);
          }
          break;

        case 4:
          this.createdAt = in.readString(this.createdAt instanceof Utf8 ? (Utf8)this.createdAt : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










