/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8229029854715947365L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionEvent\",\"namespace\":\"com.example.avro\",\"fields\":[{\"name\":\"transactionId\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"currency\",\"type\":\"string\"},{\"name\":\"merchantId\",\"type\":\"string\"},{\"name\":\"merchantCategoryCode\",\"type\":\"string\"},{\"name\":\"cardToken\",\"type\":\"string\"},{\"name\":\"securityStatus\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"fraudStatus\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"merchantLoopStatus\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"createdAt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence transactionId;
  private double amount;
  private java.lang.CharSequence currency;
  private java.lang.CharSequence merchantId;
  private java.lang.CharSequence merchantCategoryCode;
  private java.lang.CharSequence cardToken;
  private java.lang.CharSequence securityStatus;
  private java.lang.CharSequence fraudStatus;
  private java.lang.CharSequence merchantLoopStatus;
  private java.lang.CharSequence createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionEvent() {}

  /**
   * All-args constructor.
   * @param transactionId The new value for transactionId
   * @param amount The new value for amount
   * @param currency The new value for currency
   * @param merchantId The new value for merchantId
   * @param merchantCategoryCode The new value for merchantCategoryCode
   * @param cardToken The new value for cardToken
   * @param securityStatus The new value for securityStatus
   * @param fraudStatus The new value for fraudStatus
   * @param merchantLoopStatus The new value for merchantLoopStatus
   * @param createdAt The new value for createdAt
   */
  public TransactionEvent(java.lang.CharSequence transactionId, java.lang.Double amount, java.lang.CharSequence currency, java.lang.CharSequence merchantId, java.lang.CharSequence merchantCategoryCode, java.lang.CharSequence cardToken, java.lang.CharSequence securityStatus, java.lang.CharSequence fraudStatus, java.lang.CharSequence merchantLoopStatus, java.lang.CharSequence createdAt) {
    this.transactionId = transactionId;
    this.amount = amount;
    this.currency = currency;
    this.merchantId = merchantId;
    this.merchantCategoryCode = merchantCategoryCode;
    this.cardToken = cardToken;
    this.securityStatus = securityStatus;
    this.fraudStatus = fraudStatus;
    this.merchantLoopStatus = merchantLoopStatus;
    this.createdAt = createdAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionId;
    case 1: return amount;
    case 2: return currency;
    case 3: return merchantId;
    case 4: return merchantCategoryCode;
    case 5: return cardToken;
    case 6: return securityStatus;
    case 7: return fraudStatus;
    case 8: return merchantLoopStatus;
    case 9: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionId = (java.lang.CharSequence)value$; break;
    case 1: amount = (java.lang.Double)value$; break;
    case 2: currency = (java.lang.CharSequence)value$; break;
    case 3: merchantId = (java.lang.CharSequence)value$; break;
    case 4: merchantCategoryCode = (java.lang.CharSequence)value$; break;
    case 5: cardToken = (java.lang.CharSequence)value$; break;
    case 6: securityStatus = (java.lang.CharSequence)value$; break;
    case 7: fraudStatus = (java.lang.CharSequence)value$; break;
    case 8: merchantLoopStatus = (java.lang.CharSequence)value$; break;
    case 9: createdAt = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public java.lang.CharSequence getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.CharSequence value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'merchantId' field.
   * @return The value of the 'merchantId' field.
   */
  public java.lang.CharSequence getMerchantId() {
    return merchantId;
  }


  /**
   * Sets the value of the 'merchantId' field.
   * @param value the value to set.
   */
  public void setMerchantId(java.lang.CharSequence value) {
    this.merchantId = value;
  }

  /**
   * Gets the value of the 'merchantCategoryCode' field.
   * @return The value of the 'merchantCategoryCode' field.
   */
  public java.lang.CharSequence getMerchantCategoryCode() {
    return merchantCategoryCode;
  }


  /**
   * Sets the value of the 'merchantCategoryCode' field.
   * @param value the value to set.
   */
  public void setMerchantCategoryCode(java.lang.CharSequence value) {
    this.merchantCategoryCode = value;
  }

  /**
   * Gets the value of the 'cardToken' field.
   * @return The value of the 'cardToken' field.
   */
  public java.lang.CharSequence getCardToken() {
    return cardToken;
  }


  /**
   * Sets the value of the 'cardToken' field.
   * @param value the value to set.
   */
  public void setCardToken(java.lang.CharSequence value) {
    this.cardToken = value;
  }

  /**
   * Gets the value of the 'securityStatus' field.
   * @return The value of the 'securityStatus' field.
   */
  public java.lang.CharSequence getSecurityStatus() {
    return securityStatus;
  }


  /**
   * Sets the value of the 'securityStatus' field.
   * @param value the value to set.
   */
  public void setSecurityStatus(java.lang.CharSequence value) {
    this.securityStatus = value;
  }

  /**
   * Gets the value of the 'fraudStatus' field.
   * @return The value of the 'fraudStatus' field.
   */
  public java.lang.CharSequence getFraudStatus() {
    return fraudStatus;
  }


  /**
   * Sets the value of the 'fraudStatus' field.
   * @param value the value to set.
   */
  public void setFraudStatus(java.lang.CharSequence value) {
    this.fraudStatus = value;
  }

  /**
   * Gets the value of the 'merchantLoopStatus' field.
   * @return The value of the 'merchantLoopStatus' field.
   */
  public java.lang.CharSequence getMerchantLoopStatus() {
    return merchantLoopStatus;
  }


  /**
   * Sets the value of the 'merchantLoopStatus' field.
   * @param value the value to set.
   */
  public void setMerchantLoopStatus(java.lang.CharSequence value) {
    this.merchantLoopStatus = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.lang.CharSequence getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.CharSequence value) {
    this.createdAt = value;
  }

  /**
   * Creates a new TransactionEvent RecordBuilder.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.example.avro.TransactionEvent.Builder newBuilder() {
    return new com.example.avro.TransactionEvent.Builder();
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.example.avro.TransactionEvent.Builder newBuilder(com.example.avro.TransactionEvent.Builder other) {
    if (other == null) {
      return new com.example.avro.TransactionEvent.Builder();
    } else {
      return new com.example.avro.TransactionEvent.Builder(other);
    }
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing TransactionEvent instance.
   * @param other The existing instance to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.example.avro.TransactionEvent.Builder newBuilder(com.example.avro.TransactionEvent other) {
    if (other == null) {
      return new com.example.avro.TransactionEvent.Builder();
    } else {
      return new com.example.avro.TransactionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionEvent>
    implements org.apache.avro.data.RecordBuilder<TransactionEvent> {

    private java.lang.CharSequence transactionId;
    private double amount;
    private java.lang.CharSequence currency;
    private java.lang.CharSequence merchantId;
    private java.lang.CharSequence merchantCategoryCode;
    private java.lang.CharSequence cardToken;
    private java.lang.CharSequence securityStatus;
    private java.lang.CharSequence fraudStatus;
    private java.lang.CharSequence merchantLoopStatus;
    private java.lang.CharSequence createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.TransactionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[3].schema(), other.merchantId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.merchantCategoryCode)) {
        this.merchantCategoryCode = data().deepCopy(fields()[4].schema(), other.merchantCategoryCode);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.cardToken)) {
        this.cardToken = data().deepCopy(fields()[5].schema(), other.cardToken);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.securityStatus)) {
        this.securityStatus = data().deepCopy(fields()[6].schema(), other.securityStatus);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.fraudStatus)) {
        this.fraudStatus = data().deepCopy(fields()[7].schema(), other.fraudStatus);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.merchantLoopStatus)) {
        this.merchantLoopStatus = data().deepCopy(fields()[8].schema(), other.merchantLoopStatus);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[9].schema(), other.createdAt);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.TransactionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[3].schema(), other.merchantId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.merchantCategoryCode)) {
        this.merchantCategoryCode = data().deepCopy(fields()[4].schema(), other.merchantCategoryCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cardToken)) {
        this.cardToken = data().deepCopy(fields()[5].schema(), other.cardToken);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.securityStatus)) {
        this.securityStatus = data().deepCopy(fields()[6].schema(), other.securityStatus);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.fraudStatus)) {
        this.fraudStatus = data().deepCopy(fields()[7].schema(), other.fraudStatus);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.merchantLoopStatus)) {
        this.merchantLoopStatus = data().deepCopy(fields()[8].schema(), other.merchantLoopStatus);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[9].schema(), other.createdAt);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setTransactionId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.transactionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearTransactionId() {
      transactionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setAmount(double value) {
      validate(fields()[1], value);
      this.amount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearAmount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.currency = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchantId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantId() {
      return merchantId;
    }


    /**
      * Sets the value of the 'merchantId' field.
      * @param value The value of 'merchantId'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setMerchantId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.merchantId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantId' field has been set.
      * @return True if the 'merchantId' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'merchantId' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearMerchantId() {
      merchantId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchantCategoryCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantCategoryCode() {
      return merchantCategoryCode;
    }


    /**
      * Sets the value of the 'merchantCategoryCode' field.
      * @param value The value of 'merchantCategoryCode'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setMerchantCategoryCode(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.merchantCategoryCode = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantCategoryCode' field has been set.
      * @return True if the 'merchantCategoryCode' field has been set, false otherwise.
      */
    public boolean hasMerchantCategoryCode() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'merchantCategoryCode' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearMerchantCategoryCode() {
      merchantCategoryCode = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'cardToken' field.
      * @return The value.
      */
    public java.lang.CharSequence getCardToken() {
      return cardToken;
    }


    /**
      * Sets the value of the 'cardToken' field.
      * @param value The value of 'cardToken'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setCardToken(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.cardToken = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'cardToken' field has been set.
      * @return True if the 'cardToken' field has been set, false otherwise.
      */
    public boolean hasCardToken() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'cardToken' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearCardToken() {
      cardToken = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'securityStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getSecurityStatus() {
      return securityStatus;
    }


    /**
      * Sets the value of the 'securityStatus' field.
      * @param value The value of 'securityStatus'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setSecurityStatus(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.securityStatus = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'securityStatus' field has been set.
      * @return True if the 'securityStatus' field has been set, false otherwise.
      */
    public boolean hasSecurityStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'securityStatus' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearSecurityStatus() {
      securityStatus = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'fraudStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getFraudStatus() {
      return fraudStatus;
    }


    /**
      * Sets the value of the 'fraudStatus' field.
      * @param value The value of 'fraudStatus'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setFraudStatus(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.fraudStatus = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'fraudStatus' field has been set.
      * @return True if the 'fraudStatus' field has been set, false otherwise.
      */
    public boolean hasFraudStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'fraudStatus' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearFraudStatus() {
      fraudStatus = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchantLoopStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantLoopStatus() {
      return merchantLoopStatus;
    }


    /**
      * Sets the value of the 'merchantLoopStatus' field.
      * @param value The value of 'merchantLoopStatus'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setMerchantLoopStatus(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.merchantLoopStatus = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantLoopStatus' field has been set.
      * @return True if the 'merchantLoopStatus' field has been set, false otherwise.
      */
    public boolean hasMerchantLoopStatus() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'merchantLoopStatus' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearMerchantLoopStatus() {
      merchantLoopStatus = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder setCreatedAt(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.createdAt = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.example.avro.TransactionEvent.Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionEvent build() {
      try {
        TransactionEvent record = new TransactionEvent();
        record.transactionId = fieldSetFlags()[0] ? this.transactionId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.amount = fieldSetFlags()[1] ? this.amount : (java.lang.Double) defaultValue(fields()[1]);
        record.currency = fieldSetFlags()[2] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.merchantId = fieldSetFlags()[3] ? this.merchantId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.merchantCategoryCode = fieldSetFlags()[4] ? this.merchantCategoryCode : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.cardToken = fieldSetFlags()[5] ? this.cardToken : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.securityStatus = fieldSetFlags()[6] ? this.securityStatus : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.fraudStatus = fieldSetFlags()[7] ? this.fraudStatus : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.merchantLoopStatus = fieldSetFlags()[8] ? this.merchantLoopStatus : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.createdAt = fieldSetFlags()[9] ? this.createdAt : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionEvent>
    READER$ = (org.apache.avro.io.DatumReader<TransactionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.transactionId);

    out.writeDouble(this.amount);

    out.writeString(this.currency);

    out.writeString(this.merchantId);

    out.writeString(this.merchantCategoryCode);

    out.writeString(this.cardToken);

    if (this.securityStatus == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.securityStatus);
    }

    if (this.fraudStatus == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.fraudStatus);
    }

    if (this.merchantLoopStatus == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.merchantLoopStatus);
    }

    out.writeString(this.createdAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);

      this.amount = in.readDouble();

      this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);

      this.merchantId = in.readString(this.merchantId instanceof Utf8 ? (Utf8)this.merchantId : null);

      this.merchantCategoryCode = in.readString(this.merchantCategoryCode instanceof Utf8 ? (Utf8)this.merchantCategoryCode : null);

      this.cardToken = in.readString(this.cardToken instanceof Utf8 ? (Utf8)this.cardToken : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.securityStatus = null;
      } else {
        this.securityStatus = in.readString(this.securityStatus instanceof Utf8 ? (Utf8)this.securityStatus : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.fraudStatus = null;
      } else {
        this.fraudStatus = in.readString(this.fraudStatus instanceof Utf8 ? (Utf8)this.fraudStatus : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.merchantLoopStatus = null;
      } else {
        this.merchantLoopStatus = in.readString(this.merchantLoopStatus instanceof Utf8 ? (Utf8)this.merchantLoopStatus : null);
      }

      this.createdAt = in.readString(this.createdAt instanceof Utf8 ? (Utf8)this.createdAt : null);

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);
          break;

        case 1:
          this.amount = in.readDouble();
          break;

        case 2:
          this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
          break;

        case 3:
          this.merchantId = in.readString(this.merchantId instanceof Utf8 ? (Utf8)this.merchantId : null);
          break;

        case 4:
          this.merchantCategoryCode = in.readString(this.merchantCategoryCode instanceof Utf8 ? (Utf8)this.merchantCategoryCode : null);
          break;

        case 5:
          this.cardToken = in.readString(this.cardToken instanceof Utf8 ? (Utf8)this.cardToken : null);
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.securityStatus = null;
          } else {
            this.securityStatus = in.readString(this.securityStatus instanceof Utf8 ? (Utf8)this.securityStatus : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fraudStatus = null;
          } else {
            this.fraudStatus = in.readString(this.fraudStatus instanceof Utf8 ? (Utf8)this.fraudStatus : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.merchantLoopStatus = null;
          } else {
            this.merchantLoopStatus = in.readString(this.merchantLoopStatus instanceof Utf8 ? (Utf8)this.merchantLoopStatus : null);
          }
          break;

        case 9:
          this.createdAt = in.readString(this.createdAt instanceof Utf8 ? (Utf8)this.createdAt : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










